package dok.zztmm.mapper;

import dok.zztmm.entity.Authority;
import dok.zztmm.entity.AuthorityExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AuthorityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.authority
	 * @mbg.generated  Tue Dec 20 22:27:35 KST 2016
	 */
	long countByExample(AuthorityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.authority
	 * @mbg.generated  Tue Dec 20 22:27:35 KST 2016
	 */
	int deleteByExample(AuthorityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.authority
	 * @mbg.generated  Tue Dec 20 22:27:35 KST 2016
	 */
	int insert(Authority record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.authority
	 * @mbg.generated  Tue Dec 20 22:27:35 KST 2016
	 */
	int insertSelective(Authority record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.authority
	 * @mbg.generated  Tue Dec 20 22:27:35 KST 2016
	 */
	List<Authority> selectByExample(AuthorityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.authority
	 * @mbg.generated  Tue Dec 20 22:27:35 KST 2016
	 */
	int updateByExampleSelective(@Param("record") Authority record, @Param("example") AuthorityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.authority
	 * @mbg.generated  Tue Dec 20 22:27:35 KST 2016
	 */
	int updateByExample(@Param("record") Authority record, @Param("example") AuthorityExample example);
}