package dok.zztmm.mapper;

import dok.zztmm.entity.User;
import dok.zztmm.entity.UserExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.user
	 * @mbg.generated  Tue Dec 20 22:27:35 KST 2016
	 */
	long countByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.user
	 * @mbg.generated  Tue Dec 20 22:27:35 KST 2016
	 */
	int deleteByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.user
	 * @mbg.generated  Tue Dec 20 22:27:35 KST 2016
	 */
	int deleteByPrimaryKey(String username);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.user
	 * @mbg.generated  Tue Dec 20 22:27:35 KST 2016
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.user
	 * @mbg.generated  Tue Dec 20 22:27:35 KST 2016
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.user
	 * @mbg.generated  Tue Dec 20 22:27:35 KST 2016
	 */
	List<User> selectByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.user
	 * @mbg.generated  Tue Dec 20 22:27:35 KST 2016
	 */
	User selectByPrimaryKey(String username);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.user
	 * @mbg.generated  Tue Dec 20 22:27:35 KST 2016
	 */
	int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.user
	 * @mbg.generated  Tue Dec 20 22:27:35 KST 2016
	 */
	int updateByExample(@Param("record") User record, @Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.user
	 * @mbg.generated  Tue Dec 20 22:27:35 KST 2016
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.user
	 * @mbg.generated  Tue Dec 20 22:27:35 KST 2016
	 */
	int updateByPrimaryKey(User record);

	public List<String> readAuthority(String username);
	
	public int insertCustom(User user);
}