package dok.zztmm.entity;

public class Authority {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.authority.authority_name
	 * @mbg.generated  Tue Dec 20 22:27:35 KST 2016
	 */
	private String authorityName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.authority.username
	 * @mbg.generated  Tue Dec 20 22:27:35 KST 2016
	 */
	private String username;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.authority.authority_name
	 * @return  the value of public.authority.authority_name
	 * @mbg.generated  Tue Dec 20 22:27:35 KST 2016
	 */
	public String getAuthorityName() {
		return authorityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.authority.authority_name
	 * @param authorityName  the value for public.authority.authority_name
	 * @mbg.generated  Tue Dec 20 22:27:35 KST 2016
	 */
	public void setAuthorityName(String authorityName) {
		this.authorityName = authorityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.authority.username
	 * @return  the value of public.authority.username
	 * @mbg.generated  Tue Dec 20 22:27:35 KST 2016
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.authority.username
	 * @param username  the value for public.authority.username
	 * @mbg.generated  Tue Dec 20 22:27:35 KST 2016
	 */
	public void setUsername(String username) {
		this.username = username;
	}
}