package dok.zztmm.entity;

public class Authority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.authority.user_id
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.authority.authority_name
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    private String authorityName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.authority.user_id
     *
     * @return the value of public.authority.user_id
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.authority.user_id
     *
     * @param userId the value for public.authority.user_id
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.authority.authority_name
     *
     * @return the value of public.authority.authority_name
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    public String getAuthorityName() {
        return authorityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.authority.authority_name
     *
     * @param authorityName the value for public.authority.authority_name
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    public void setAuthorityName(String authorityName) {
        this.authorityName = authorityName;
    }
}