package dok.zztmm.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user.id
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user.email
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user.password
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user.username
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user.realname
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user.phonenumber
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    private String phonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user.isAccountNonExpried
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    private Boolean isaccountnonexpried;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user.isAccountNonLocked
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    private Boolean isaccountnonlocked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user.isCredentialsNonExpried
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    private Boolean iscredentialsnonexpried;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user.isEnabled
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    private Boolean isenabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user.id
     *
     * @return the value of public.user.id
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user.id
     *
     * @param id the value for public.user.id
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user.email
     *
     * @return the value of public.user.email
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user.email
     *
     * @param email the value for public.user.email
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user.password
     *
     * @return the value of public.user.password
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user.password
     *
     * @param password the value for public.user.password
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user.username
     *
     * @return the value of public.user.username
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user.username
     *
     * @param username the value for public.user.username
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user.realname
     *
     * @return the value of public.user.realname
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user.realname
     *
     * @param realname the value for public.user.realname
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user.phonenumber
     *
     * @return the value of public.user.phonenumber
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user.phonenumber
     *
     * @param phonenumber the value for public.user.phonenumber
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user.isAccountNonExpried
     *
     * @return the value of public.user.isAccountNonExpried
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    public Boolean getIsaccountnonexpried() {
        return isaccountnonexpried;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user.isAccountNonExpried
     *
     * @param isaccountnonexpried the value for public.user.isAccountNonExpried
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    public void setIsaccountnonexpried(Boolean isaccountnonexpried) {
        this.isaccountnonexpried = isaccountnonexpried;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user.isAccountNonLocked
     *
     * @return the value of public.user.isAccountNonLocked
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    public Boolean getIsaccountnonlocked() {
        return isaccountnonlocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user.isAccountNonLocked
     *
     * @param isaccountnonlocked the value for public.user.isAccountNonLocked
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    public void setIsaccountnonlocked(Boolean isaccountnonlocked) {
        this.isaccountnonlocked = isaccountnonlocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user.isCredentialsNonExpried
     *
     * @return the value of public.user.isCredentialsNonExpried
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    public Boolean getIscredentialsnonexpried() {
        return iscredentialsnonexpried;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user.isCredentialsNonExpried
     *
     * @param iscredentialsnonexpried the value for public.user.isCredentialsNonExpried
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    public void setIscredentialsnonexpried(Boolean iscredentialsnonexpried) {
        this.iscredentialsnonexpried = iscredentialsnonexpried;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user.isEnabled
     *
     * @return the value of public.user.isEnabled
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    public Boolean getIsenabled() {
        return isenabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user.isEnabled
     *
     * @param isenabled the value for public.user.isEnabled
     *
     * @mbg.generated Mon Dec 19 21:55:30 JST 2016
     */
    public void setIsenabled(Boolean isenabled) {
        this.isenabled = isenabled;
    }
}